### ISSUE TITLE
Book order form

### ISSUE THREAD

**Issue by tobiasf** [jjmmkk/diktkassa#25]
I think it would be a good idea to have a form for ordering the book. I am not thinking anything complicated, but this is my proposal:

A form with relevant fields for name and address and stuff. 
The form sends an email to our email address on submittion. 
The customer gets an automatic reply with this ish "Hello, thank you for your order. You will get some information soon".
We manually send giro to customer
When we receive payment, we will send the book.

**Comment by jjmmkk** [comment]
Branch _book-form_.
Add to .env.php:
```php
<?php
return [
    …
    'order_email' => 'that_secret_email@you_know.com',
```

**Comment by tobiasf** [comment]
Add field for email and field for freetext.
When you click "Bestill", show confirmation page with the order, and a message that they have to confirm their order.

**Comment by tobiasf** [comment]
Forslag til tekst over skjemaet (kun et forslag):

Bruk skjemaet under for å bestille et eksemplar av boka "Norges anonyme diktere". Boka koster 100 kroner, og inkluderer frakt. Giro for betaling følger med boka. Sendes normalt innen 3 virkedager fra bestillingen er mottatt.

**Comment by jjmmkk** [comment]
Pushed to _book-form_.

**Comment by tobiasf** [comment]
Added confirmation mail to customer. Pushed to book-form.

**Comment by jjmmkk** [comment]
Merged into master.
